require 'rubots/command/base'
require 'rubots/command/rotate_to'
require 'rubots/command/throttle'
require 'rubots/command/rotate_gun_to'
require 'rubots/command/fire'
require 'rubots/command/do_nothing'
